version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      browser-dependencies:
        patterns: ["*"]
  - package-ecosystem: nuget
    directory: /src/SharpTS.Www.AppHost
    schedule:
      interval: weekly
    groups:
      aspire-dependencies:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
