<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <SharpTSProjectReference Condition="'$(SharpTSProjectReference)' == ''">..\..\lib\SharpTS\SharpTS.csproj</SharpTSProjectReference>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SharpTSProjectReference)" />
  </ItemGroup>

</Project>
