[CmdletBinding()]
param(
    [string]$PublicRoot = (Join-Path (Split-Path -Parent $PSScriptRoot) "artifacts/self-host/public")
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Assert-True {
    param([object]$Condition, [string]$Message)
    if (-not [bool]$Condition) { throw $Message }
}

$resolvedRoot = [IO.Path]::GetFullPath($PublicRoot)
$manifestPath = Join-Path $resolvedRoot "site-manifest.json"
Assert-True (Test-Path -LiteralPath $manifestPath -PathType Leaf) "Generated site manifest is missing."

$manifest = Get-Content -Raw -LiteralPath $manifestPath | ConvertFrom-Json
$repoRoot = Split-Path -Parent $PSScriptRoot
$expectedStylesheetSources = @(Get-ChildItem -LiteralPath `
    (Join-Path $repoRoot "src/SharpTS.Www.SelfHost/styles") -Filter "*.css" -File).Count
$expectedResourceFiles = @(Get-ChildItem -LiteralPath `
    (Join-Path $repoRoot "src/SharpTS.Www.SelfHost/locales") -Filter "*.resx" -File).Count
Assert-True ($manifest.generatedBy -eq "SharpTS") "Site was not generated by SharpTS."
Assert-True (@($manifest.cultures).Count -eq 5) "Expected five generated cultures."
Assert-True (@($manifest.routes).Count -eq 15) "Expected fifteen generated routes."
Assert-True ($manifest.stylesheetSources -eq $expectedStylesheetSources) `
    "Manifest stylesheet count does not match the source directory."
Assert-True ($manifest.resourceFiles -eq $expectedResourceFiles) `
    "Manifest resource count does not match the locale directory."
Assert-True (@($manifest.browserBundle).Count -ge 2) "Expected browser JavaScript and CSS bundles."
Assert-True (Test-Path -LiteralPath (Join-Path $resolvedRoot "conformance.json") -PathType Leaf) `
    "Aggregated conformance data is missing."
Assert-True (-not [string]::IsNullOrWhiteSpace($manifest.browserEntry.script)) `
    "Browser script entry is missing from the manifest."
Assert-True (-not [string]::IsNullOrWhiteSpace($manifest.browserEntry.style)) `
    "Browser style entry is missing from the manifest."

$allowedRoot = $resolvedRoot.TrimEnd([IO.Path]::DirectorySeparatorChar) + [IO.Path]::DirectorySeparatorChar

function Resolve-LocalReference {
    param([string]$Reference)

    $pathOnly = ($Reference -split '[?#]', 2)[0]
    if ([string]::IsNullOrEmpty($pathOnly)) { return $null }
    $relative = $pathOnly.TrimStart('/').Replace('/', [IO.Path]::DirectorySeparatorChar)
    if ([string]::IsNullOrEmpty($relative)) { $relative = "index.html" }
    elseif ([string]::IsNullOrEmpty([IO.Path]::GetExtension($relative))) {
        $relative = Join-Path $relative "index.html"
    }
    return [IO.Path]::GetFullPath((Join-Path $resolvedRoot $relative))
}

$pageSummaries = @()
foreach ($route in $manifest.routes) {
    $filePath = [IO.Path]::GetFullPath((Join-Path $resolvedRoot $route.file))
    Assert-True ($filePath.StartsWith($allowedRoot, [StringComparison]::OrdinalIgnoreCase)) `
        "Generated route escaped the public root: $($route.file)"
    Assert-True (Test-Path -LiteralPath $filePath -PathType Leaf) `
        "Generated route file is missing: $($route.file)"

    $html = Get-Content -Raw -LiteralPath $filePath
    $head = [regex]::Match($html, '(?s)<head>(.*?)</head>').Groups[1].Value
    $expectedCanonical = "https://sharpts.dev$($route.route)"
    Assert-True ($html.Contains("<html lang=`"$($route.culture)`">")) `
        "Incorrect html lang for $($route.route)."
    Assert-True ($head.Contains("rel=`"canonical`" href=`"$expectedCanonical`"")) `
        "Incorrect canonical URL for $($route.route)."
    Assert-True (([regex]::Matches($head, 'rel="alternate" hreflang=')).Count -eq 6) `
        "Expected five locale alternates plus x-default for $($route.route)."
    Assert-True (-not [string]::IsNullOrWhiteSpace([regex]::Match($head, '<title>(.*?)</title>').Groups[1].Value)) `
        "Missing title for $($route.route)."

    if ($route.page -eq "conformance") {
        Assert-True ($html.Contains('<details class="conformance__node')) `
            "Conformance tree is missing from $($route.route)."
        Assert-True (-not $html.Contains('<script')) `
            "Conformance route $($route.route) must remain JavaScript-free."
    }

    foreach ($legacyMarker in @('_framework/', 'blazor.web.js', 'SharpTS.Www.Web.styles.css',
            'href="css/', 'src="img/', 'src="js/', '@inject', '@L[')) {
        Assert-True (-not $html.Contains($legacyMarker)) `
            "Legacy marker '$legacyMarker' remains in $($route.file)."
    }

    $references = [regex]::Matches($html, '(?:href|src)="([^"]+)"') |
        ForEach-Object { $_.Groups[1].Value } |
        Where-Object { $_.StartsWith('/') }
    foreach ($reference in $references) {
        $target = Resolve-LocalReference $reference
        if ($null -eq $target) { continue }
        Assert-True ($target.StartsWith($allowedRoot, [StringComparison]::OrdinalIgnoreCase)) `
            "Local reference escaped the public root: $reference"
        Assert-True (Test-Path -LiteralPath $target -PathType Leaf) `
            "Broken local reference '$reference' in $($route.file)."
    }

    $pageSummaries += [pscustomobject]@{
        culture = $route.culture
        page = $route.page
        route = $route.route
        bytes = (Get-Item -LiteralPath $filePath).Length
    }
}

$cssPath = Join-Path $resolvedRoot "css/site.css"
$css = Get-Content -Raw -LiteralPath $cssPath
Assert-True (-not $css.Contains('::deep')) "CSS bundle contains a Blazor ::deep selector."
foreach ($selector in @('.hero', '.features-grid', '.pipeline', '.playground', '.lang-selector', '.conformance', '.footer')) {
    Assert-True ($css.Contains($selector)) "CSS bundle is missing $selector."
}

$browserJavaScriptPath = Join-Path $resolvedRoot $manifest.browserEntry.script
$browserCssPath = Join-Path $resolvedRoot $manifest.browserEntry.style
Assert-True (Test-Path -LiteralPath $browserJavaScriptPath -PathType Leaf) `
    "Browser JavaScript bundle is missing."
Assert-True (Test-Path -LiteralPath $browserCssPath -PathType Leaf) `
    "Browser CSS bundle is missing."
$browserJavaScript = Get-Content -Raw -LiteralPath $browserJavaScriptPath
foreach ($remoteMarker in @('esm.sh', 'cdnjs.cloudflare.com', 'fonts.googleapis.com',
        'clarity.ms', 'invokeMethodAsync', 'dotNetRef')) {
    Assert-True (-not $browserJavaScript.Contains($remoteMarker)) `
        "Browser bundle contains forbidden remote or Blazor marker '$remoteMarker'."
}
$browserCss = Get-Content -Raw -LiteralPath $browserCssPath
$fontReferences = [regex]::Matches($browserCss, 'url\((?:"|''|)([^)"'']+)(?:"|''|)\)') |
    ForEach-Object { $_.Groups[1].Value }
Assert-True (@($fontReferences).Count -gt 0) "Browser CSS does not reference self-hosted fonts."
foreach ($fontReference in $fontReferences) {
    $fontPath = [IO.Path]::GetFullPath((Join-Path (Split-Path -Parent $browserCssPath) $fontReference))
    Assert-True ($fontPath.StartsWith($allowedRoot, [StringComparison]::OrdinalIgnoreCase)) `
        "Browser font reference escaped the public root: $fontReference"
    Assert-True (Test-Path -LiteralPath $fontPath -PathType Leaf) `
        "Browser font reference is missing: $fontReference"
}

$snapshotPath = Join-Path $repoRoot "src/SharpTS.Www.SelfHost/site.snapshot.json"
Assert-True (Test-Path -LiteralPath $snapshotPath -PathType Leaf) "Generated-site snapshot is missing."
$snapshot = Get-Content -Raw -LiteralPath $snapshotPath | ConvertFrom-Json
Assert-True ($snapshot.version -eq 2) "Unsupported generated-site snapshot version."
Assert-True (@($snapshot.files).Count -ge 13) `
    "Expected HTML, site CSS, and browser bundle snapshots."
foreach ($entry in $snapshot.files) {
    $snapshotFile = [IO.Path]::GetFullPath((Join-Path $resolvedRoot $entry.path))
    Assert-True ($snapshotFile.StartsWith($allowedRoot, [StringComparison]::OrdinalIgnoreCase)) `
        "Snapshot path escaped the public root: $($entry.path)"
    Assert-True (Test-Path -LiteralPath $snapshotFile -PathType Leaf) `
        "Snapshot target is missing: $($entry.path)"
    $actualHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $snapshotFile).Hash.ToLowerInvariant()
    Assert-True ($actualHash -eq $entry.sha256) `
        "Generated output changed for $($entry.path). Review the diff and update site.snapshot.json intentionally."
}

[pscustomobject]@{
    generator = $manifest.generatedBy
    cultures = @($manifest.cultures).Count
    routes = @($manifest.routes).Count
    snapshots = @($snapshot.files).Count
    cssBytes = (Get-Item -LiteralPath $cssPath).Length
    pages = $pageSummaries
} | ConvertTo-Json -Depth 5
