[CmdletBinding()]
param(
    [string]$PublicRoot = (Join-Path (Split-Path -Parent $PSScriptRoot) "artifacts/self-host/public")
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Assert-True {
    param([object]$Condition, [string]$Message)
    if (-not [bool]$Condition) { throw $Message }
}

$resolvedRoot = [IO.Path]::GetFullPath($PublicRoot)
$manifestPath = Join-Path $resolvedRoot "site-manifest.json"
Assert-True (Test-Path -LiteralPath $manifestPath -PathType Leaf) "Generated site manifest is missing."

$manifest = Get-Content -Raw -LiteralPath $manifestPath | ConvertFrom-Json
$repoRoot = Split-Path -Parent $PSScriptRoot
$expectedStylesheetSources = @(Get-ChildItem -LiteralPath `
    (Join-Path $repoRoot "src/SharpTS.Www.SelfHost/styles") -Filter "*.css" -File).Count
$expectedMessageFiles = @(Get-ChildItem -LiteralPath `
    (Join-Path $repoRoot "src/SharpTS.Www.SelfHost/locales") -Filter "*.json" -File -Recurse).Count
Assert-True ($manifest.generatedBy -eq "SharpTS") "Site was not generated by SharpTS."
Assert-True (@($manifest.cultures).Count -eq 5) "Expected five generated cultures."
Assert-True (@($manifest.routes).Count -eq 210) "Expected 210 generated routes."
Assert-True ($manifest.stylesheetSources -eq $expectedStylesheetSources) `
    "Manifest stylesheet count does not match the source directory."
Assert-True ($manifest.messageFiles -eq $expectedMessageFiles) `
    "Manifest message count does not match the locale directory."
Assert-True (@($manifest.browserBundle).Count -ge 2) "Expected browser JavaScript and CSS bundles."
Assert-True (Test-Path -LiteralPath (Join-Path $resolvedRoot "conformance.json") -PathType Leaf) `
    "Aggregated conformance data is missing."
Assert-True (-not [string]::IsNullOrWhiteSpace($manifest.browserEntry.script)) `
    "Browser script entry is missing from the manifest."
Assert-True (-not [string]::IsNullOrWhiteSpace($manifest.browserEntry.style)) `
    "Browser style entry is missing from the manifest."
Assert-True (-not [string]::IsNullOrWhiteSpace($manifest.browserEntry.conformanceScript)) `
    "Conformance browser entry is missing from the manifest."
Assert-True (-not [string]::IsNullOrWhiteSpace($manifest.browserEntry.docsScript)) `
    "Documentation browser entry is missing from the manifest."
Assert-True ($manifest.stylesheet -match '^css/site-[0-9a-f]{8}\.css$') `
    "Site stylesheet is not content fingerprinted."

$allowedRoot = $resolvedRoot.TrimEnd([IO.Path]::DirectorySeparatorChar) + [IO.Path]::DirectorySeparatorChar

function Resolve-LocalReference {
    param([string]$Reference)

    $pathOnly = ($Reference -split '[?#]', 2)[0]
    if ([string]::IsNullOrEmpty($pathOnly)) { return $null }
    $relative = $pathOnly.TrimStart('/').Replace('/', [IO.Path]::DirectorySeparatorChar)
    if ([string]::IsNullOrEmpty($relative)) { $relative = "index.html" }
    elseif ([string]::IsNullOrEmpty([IO.Path]::GetExtension($relative))) {
        $relative = Join-Path $relative "index.html"
    }
    return [IO.Path]::GetFullPath((Join-Path $resolvedRoot $relative))
}

$pageSummaries = @()
foreach ($route in $manifest.routes) {
    $filePath = [IO.Path]::GetFullPath((Join-Path $resolvedRoot $route.file))
    Assert-True ($filePath.StartsWith($allowedRoot, [StringComparison]::OrdinalIgnoreCase)) `
        "Generated route escaped the public root: $($route.file)"
    Assert-True (Test-Path -LiteralPath $filePath -PathType Leaf) `
        "Generated route file is missing: $($route.file)"

    $html = Get-Content -Raw -LiteralPath $filePath
    $head = [regex]::Match($html, '(?s)<head>(.*?)</head>').Groups[1].Value
    $expectedCanonical = "https://sharpts.dev$($route.route)"
    Assert-True ($html.Contains("<html lang=`"$($route.culture)`">")) `
        "Incorrect html lang for $($route.route)."
    Assert-True ($head.Contains("rel=`"canonical`" href=`"$expectedCanonical`"")) `
        "Incorrect canonical URL for $($route.route)."
    $expectedAlternates = if ($route.page -in @("docs", "api")) { 0 } else { 6 }
    Assert-True (([regex]::Matches($head, 'rel="alternate" hreflang=')).Count -eq $expectedAlternates) `
        "Unexpected locale alternate count for $($route.route)."
    Assert-True (-not [string]::IsNullOrWhiteSpace([regex]::Match($head, '<title>(.*?)</title>').Groups[1].Value)) `
        "Missing title for $($route.route)."

    if ($route.page -eq "conformance") {
        Assert-True ($html.Contains('<details class="conformance__node')) `
            "Conformance tree is missing from $($route.route)."
        Assert-True ($html.Contains("src=`"/$($manifest.browserEntry.conformanceScript)`"")) `
            "Conformance route $($route.route) is missing its explorer bundle."
        Assert-True ($html.Contains('data-conformance-suite="test262"')) `
            "Test262 section is missing from $($route.route)."
        Assert-True ($html.Contains('data-conformance-suite="typescript"')) `
            "TypeScript section is missing from $($route.route)."
    }
    if ($route.page -eq "docs") {
        Assert-True ($route.culture -eq "en") "Documentation routes must be English-first."
        Assert-True ($html.Contains('data-docs-sidebar')) "Documentation sidebar is missing."
        Assert-True ($html.Contains('data-docs-outline')) "Documentation outline is missing."
        Assert-True ($html.Contains('Tested with SharpTS')) "Tested version is missing."
        Assert-True ($html.Contains("src=`"/$($manifest.browserEntry.docsScript)`"")) `
            "Documentation route $($route.route) is missing its lightweight bundle."
        Assert-True (-not $html.Contains('<arrow fn>') -and -not $html.Contains('&lt;arrow fn&gt;')) `
            "Documentation route $($route.route) leaked an internal SharpTS function representation."
    }
    if ($route.page -eq "api") {
        Assert-True ($route.culture -eq "en") "API reference routes must be English-first."
        Assert-True ($html.Contains('data-docs-sidebar')) "API reference sidebar is missing."
        Assert-True ($html.Contains('data-docs-outline')) "API reference outline is missing."
        Assert-True ($html.Contains('data-api-search')) "API search is missing."
        Assert-True ($html.Contains('@sharpts/gui')) "API package identity is missing."
        Assert-True ($html.Contains("src=`"/$($manifest.browserEntry.docsScript)`"")) `
            "API reference route $($route.route) is missing its lightweight bundle."
        Assert-True (-not $html.Contains('<arrow fn>') -and -not $html.Contains('&lt;arrow fn&gt;')) `
            "API reference route $($route.route) leaked an internal SharpTS function representation."
    }

    foreach ($legacyMarker in @('_framework/', 'blazor.web.js', 'SharpTS.Www.Web.styles.css',
            'href="css/', 'src="img/', 'src="js/', '@inject', '@L[')) {
        Assert-True (-not $html.Contains($legacyMarker)) `
            "Legacy marker '$legacyMarker' remains in $($route.file)."
    }

    $references = [regex]::Matches($html, '(?:href|src)="([^"]+)"') |
        ForEach-Object { $_.Groups[1].Value } |
        Where-Object { $_.StartsWith('/') }
    foreach ($reference in $references) {
        $target = Resolve-LocalReference $reference
        if ($null -eq $target) { continue }
        Assert-True ($target.StartsWith($allowedRoot, [StringComparison]::OrdinalIgnoreCase)) `
            "Local reference escaped the public root: $reference"
        Assert-True (Test-Path -LiteralPath $target -PathType Leaf) `
            "Broken local reference '$reference' in $($route.file)."
    }

    $pageSummaries += [pscustomobject]@{
        culture = $route.culture
        page = $route.page
        route = $route.route
        bytes = (Get-Item -LiteralPath $filePath).Length
    }
}

$cssPath = Join-Path $resolvedRoot $manifest.stylesheet
$css = Get-Content -Raw -LiteralPath $cssPath
Assert-True (-not $css.Contains('::deep')) "CSS bundle contains a Blazor ::deep selector."
foreach ($selector in @('.hero', '.features-grid', '.pipeline', '.playground', '.lang-selector', '.conformance', '.docs-layout', '.api-search', '.api-table', '.footer')) {
    Assert-True ($css.Contains($selector)) "CSS bundle is missing $selector."
}

$browserJavaScriptPath = Join-Path $resolvedRoot $manifest.browserEntry.script
$browserCssPath = Join-Path $resolvedRoot $manifest.browserEntry.style
$conformanceJavaScriptPath = Join-Path $resolvedRoot $manifest.browserEntry.conformanceScript
$docsJavaScriptPath = Join-Path $resolvedRoot $manifest.browserEntry.docsScript
Assert-True (Test-Path -LiteralPath $browserJavaScriptPath -PathType Leaf) `
    "Browser JavaScript bundle is missing."
Assert-True (Test-Path -LiteralPath $browserCssPath -PathType Leaf) `
    "Browser CSS bundle is missing."
Assert-True (Test-Path -LiteralPath $conformanceJavaScriptPath -PathType Leaf) `
    "Conformance JavaScript bundle is missing."
Assert-True (Test-Path -LiteralPath $docsJavaScriptPath -PathType Leaf) `
    "Documentation JavaScript bundle is missing."

$docsManifestPath = Join-Path $resolvedRoot "docs-manifest.json"
$docsExamplesPath = Join-Path $resolvedRoot "docs-examples-manifest.json"
Assert-True (Test-Path -LiteralPath $docsManifestPath -PathType Leaf) "Documentation manifest is missing."
Assert-True (Test-Path -LiteralPath $docsExamplesPath -PathType Leaf) "Documentation example manifest is missing."
$docsManifest = Get-Content -Raw -LiteralPath $docsManifestPath | ConvertFrom-Json
$docsExamples = Get-Content -Raw -LiteralPath $docsExamplesPath | ConvertFrom-Json
Assert-True ($docsManifest.language -eq "en") "Documentation manifest language must be English."
Assert-True (@($docsManifest.articles).Count -eq 11) "Expected eleven published documentation articles."
Assert-True (@($docsManifest.articles).slug -contains "getting-started/desktop-gui") `
    "The desktop GUI guide must be published."
Assert-True (@($docsManifest.articles).slug -contains "getting-started/scripting") `
    "The scripting guide must be published."
Assert-True (-not (@($docsManifest.articles).slug -contains "getting-started/web-projects")) `
    "The web-projects draft must not be published."
Assert-True (@($docsExamples).Count -ge 1) "Expected at least one executable documentation example."
$apiSearchPath = Join-Path $resolvedRoot "docs/api/search-index.json"
Assert-True (Test-Path -LiteralPath $apiSearchPath -PathType Leaf) "API search index is missing."
$apiSearch = Get-Content -Raw -LiteralPath $apiSearchPath | ConvertFrom-Json
Assert-True ($apiSearch.schemaVersion -eq 1) "Unsupported API search index version."
Assert-True ($apiSearch.package -eq '@sharpts/gui') "Unexpected API search package."
Assert-True (@($apiSearch.symbols).Count -eq 174) "Expected 174 searchable API symbols."
Assert-True (@($apiSearch.symbols | Where-Object { $_.name -eq 'Button' }).Count -eq 1) `
    "Button is missing from the API search index."
$browserJavaScript = Get-Content -Raw -LiteralPath $browserJavaScriptPath
foreach ($remoteMarker in @('esm.sh', 'cdnjs.cloudflare.com', 'fonts.googleapis.com',
        'clarity.ms', 'invokeMethodAsync', 'dotNetRef')) {
    Assert-True (-not $browserJavaScript.Contains($remoteMarker)) `
        "Browser bundle contains forbidden remote or Blazor marker '$remoteMarker'."
}
$browserCss = Get-Content -Raw -LiteralPath $browserCssPath
$fontReferences = [regex]::Matches($browserCss, 'url\((?:"|''|)([^)"'']+)(?:"|''|)\)') |
    ForEach-Object { $_.Groups[1].Value }
Assert-True (@($fontReferences).Count -gt 0) "Browser CSS does not reference self-hosted fonts."
foreach ($fontReference in $fontReferences) {
    $fontPath = [IO.Path]::GetFullPath((Join-Path (Split-Path -Parent $browserCssPath) $fontReference))
    Assert-True ($fontPath.StartsWith($allowedRoot, [StringComparison]::OrdinalIgnoreCase)) `
        "Browser font reference escaped the public root: $fontReference"
    Assert-True (Test-Path -LiteralPath $fontPath -PathType Leaf) `
        "Browser font reference is missing: $fontReference"
}

$snapshotPath = Join-Path $repoRoot "src/SharpTS.Www.SelfHost/site.snapshot.json"
Assert-True (Test-Path -LiteralPath $snapshotPath -PathType Leaf) "Generated-site snapshot is missing."
$snapshot = Get-Content -Raw -LiteralPath $snapshotPath | ConvertFrom-Json
Assert-True ($snapshot.version -eq 2) "Unsupported generated-site snapshot version."
$expectedSnapshotPaths = @(
    @($manifest.routes | ForEach-Object { $_.file }) +
    @($manifest.stylesheet) +
    @($manifest.installScript) +
    @($manifest.browserBundle | Where-Object { $_ -match '\.(js|css)$' }) +
    @('docs/api/search-index.json')
) | Sort-Object -Unique
Assert-True ($manifest.installScript -eq 'setup.sh') "Generated manifest has the wrong install script path."
$generatedSetup = Join-Path $resolvedRoot $manifest.installScript
$sourceSetup = Join-Path $repoRoot 'setup.sh'
Assert-True (Test-Path -LiteralPath $generatedSetup -PathType Leaf) "Generated setup.sh is missing."
Assert-True ((Get-FileHash -Algorithm SHA256 -LiteralPath $generatedSetup).Hash -eq `
    (Get-FileHash -Algorithm SHA256 -LiteralPath $sourceSetup).Hash) `
    "Generated setup.sh does not match the repository-root source."
Assert-True (@($snapshot.files).Count -eq @($expectedSnapshotPaths).Count) `
    "Generated snapshot count does not match routes and published assets."
foreach ($entry in $snapshot.files) {
    $snapshotFile = [IO.Path]::GetFullPath((Join-Path $resolvedRoot $entry.path))
    Assert-True ($snapshotFile.StartsWith($allowedRoot, [StringComparison]::OrdinalIgnoreCase)) `
        "Snapshot path escaped the public root: $($entry.path)"
    Assert-True (Test-Path -LiteralPath $snapshotFile -PathType Leaf) `
        "Snapshot target is missing: $($entry.path)"
    $actualHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $snapshotFile).Hash.ToLowerInvariant()
    Assert-True ($actualHash -eq $entry.sha256) `
        "Generated output changed for $($entry.path). Review the diff and update site.snapshot.json intentionally."
}

[pscustomobject]@{
    generator = $manifest.generatedBy
    cultures = @($manifest.cultures).Count
    routes = @($manifest.routes).Count
    snapshots = @($snapshot.files).Count
    cssBytes = (Get-Item -LiteralPath $cssPath).Length
    pages = $pageSummaries
} | ConvertTo-Json -Depth 5
